apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat
  labels:
    app: heartbeat
data:
  SERVER_INFO: '{"root":{"url":"http://localhost:5000"},"metrics":{"url":"http://localhost:5000/metrics"}}'