apiVersion: v1
kind: ConfigMap
metadata:
  name: health-exporter
  labels:
    app: health-exporter
data:
  SERVER_INFO: '{"root":{"url":"http://localhost:5000"},"metrics":{"url":"http://localhost:5000/metrics"},"response":{"metric":"https://httpbin.org/response-headers","method":"GET","expr":"body[\"Content-Length\"]"}}'