apiVersion: v1
kind: Service
metadata:
  name: heartbeat
  labels:
    app: heartbeat
    chart: heartbeat-1.0.0
    heritage: Tiller
    release: prometheus-operator
spec:
  ports:
    - name: metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: heartbeat
    release: prometheus-operator
