apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: heartbeat
  namespace: monitoring
  labels:
    app: heartbeat
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: heartbeat
