apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-exporter
  namespace: monitoring
  labels:
    app: health-exporter
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: health-exporter
