apiVersion: v1
kind: Service
metadata:
  name: heartbeat
  labels:
    app: heartbeat
spec:
  ports:
    - name: metrics
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: heartbeat
