version: "3"

services:
  health-exporter:
    image: jianminhuang/health-exporter:latest
    ports:
      - "5000:5000"
    privileged: true
    environment:
      SERVER_INFO: '{"root":{"url":"http://localhost:5000"},"metrics":{"url":"http://localhost:5000/metrics"},"response":{"metric":"https://httpbin.org/response-headers","method":"GET","expr":"body[\"Content-Length\"]"}}'

networks:
  default: