version: "3"

services:
  heartbeat:
    image: jianminhuang/prometheus-heartbeat-exporter:1.0.1
    ports:
      - "5000:5000"
    privileged: true
    environment:
      SERVER_INFO: '{"root":{"url":"http://localhost:5000"},"server2":{"metrics":"http://localhost:5000/metrics"}}'

networks:
  default: